name: P5 Cards Browser Tests

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
  workflow_dispatch:

jobs:
  test-firefox:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: p5-cards/tests/requirements.txt

    - run: pip install -r p5-cards/tests/requirements.txt      

    - name: Install system dependencies (including Firefox)
      run: |
        sudo install -d -m 0755 /etc/apt/keyrings

        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive \
          APT_CONFIG=/dev/null \
          APT_NO_MANDATABASE=1 \
          apt-get install -y --no-install-recommends \
          xdg-utils \
          python3-pip

        wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null

        echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null

        echo '
        Package: *
        Pin: origin packages.mozilla.org
        Pin-Priority: 1000
        ' | sudo tee /etc/apt/preferences.d/mozilla

        sudo apt-get update && \
        sudo DEBIAN_FRONTEND=noninteractive \
          APT_NO_MANDATABASE=1 \
          apt-get install -y --no-install-recommends firefox

    - name: Set up Display
      run: echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Run Firefox Tests using Python
      run: |
        cd p5-cards/tests
        python firefox.py

  test-chrome:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: p5-cards/tests/requirements.txt

    - run: pip install -r p5-cards/tests/requirements.txt  

    - name: Install system dependencies (including Chrome)
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive \
          APT_CONFIG=/dev/null \
          APT_NO_MANDATABASE=1 \
          apt-get install -y --no-install-recommends \
          xdg-utils \
          gnupg \
          unzip \
          python3-pip

        # Add Google's signing key and install Chrome
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | \
          sudo tee /etc/apt/sources.list.d/google-chrome.list

        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive \
          APT_NO_MANDATABASE=1 \
          apt-get install -y --no-install-recommends google-chrome-stable

    - name: Set up Display
      run: echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Run Chrome Tests using Python
      run: |
        cd p5-cards/tests
        python chrome.py