name: Deploy to Cassini

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # This checks out your repository so that we can deploy the code

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem  # Secure the private key file

    - name: Deploy to server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client

        ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER_IP }} << 'EOF'
          ls -al

        EOF

    - name: Clean up SSH private key
      run: |
        rm -f private_key.pem