name: Deploy p5-cards to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload site content
        uses: actions/upload-pages-artifact@v3
        with:
          path: p5-cards

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
