name: P5 Cards Browser Tests

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:

jobs:
  test-firefox:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Use stable version

    - name: Install dependencies and Firefox (non-snap)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xdg-utils \
          wget \
          tar \
          xvfb \
          libdbus-glib-1-2 \
          libgtk-3-0 \
          libasound2 \
          libx11-xcb1 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          libnss3 \
          libxss1 \
          libxtst6 \
          fonts-liberation \
          libappindicator3-1 \
          libatk-bridge2.0-0 \
          libdrm2 \
          libxext6 \
          libgbm1

        # Download and extract latest Firefox from Mozilla
        wget -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
        tar -xjf firefox.tar.bz2
        sudo mv firefox /opt/firefox
        sudo ln -sf /opt/firefox/firefox /usr/local/bin/firefox

    - name: Install Python dependencies
      run: pip install selenium webdriver-manager requests

    - name: Set up virtual display
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Run Firefox Tests using Python
      run: |
        cd p5-cards/tests
        python firefox.py

  test-chrome:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Chrome and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xdg-utils \
          wget \
          gnupg \
          unzip \
          xvfb \
          python3-pip

        # Add Google's signing key and install Chrome
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | \
          sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Python dependencies
      run: pip install selenium webdriver-manager requests

    - name: Set up virtual display
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Run Chrome Tests using Python
      run: |
        cd p5-cards/tests
        python chrome.py
